// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kstor/kstor/kstor.proto

package kstor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageCn            string   `protobuf:"bytes,3,opt,name=messageCn,proto3" json:"messageCn,omitempty"`
	Stack                []string `protobuf:"bytes,4,rep,name=stack,proto3" json:"stack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f41739f9b308ed2, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetMessageCn() string {
	if m != nil {
		return m.MessageCn
	}
	return ""
}

func (m *Status) GetStack() []string {
	if m != nil {
		return m.Stack
	}
	return nil
}

type KstorRequest struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Bucketname           string   `protobuf:"bytes,4,opt,name=Bucketname,proto3" json:"Bucketname,omitempty"`
	Path                 string   `protobuf:"bytes,5,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KstorRequest) Reset()         { *m = KstorRequest{} }
func (m *KstorRequest) String() string { return proto.CompactTextString(m) }
func (*KstorRequest) ProtoMessage()    {}
func (*KstorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f41739f9b308ed2, []int{1}
}

func (m *KstorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KstorRequest.Unmarshal(m, b)
}
func (m *KstorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KstorRequest.Marshal(b, m, deterministic)
}
func (m *KstorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KstorRequest.Merge(m, src)
}
func (m *KstorRequest) XXX_Size() int {
	return xxx_messageInfo_KstorRequest.Size(m)
}
func (m *KstorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KstorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KstorRequest proto.InternalMessageInfo

func (m *KstorRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *KstorRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KstorRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *KstorRequest) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *KstorRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type KstorReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KstorReply) Reset()         { *m = KstorReply{} }
func (m *KstorReply) String() string { return proto.CompactTextString(m) }
func (*KstorReply) ProtoMessage()    {}
func (*KstorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f41739f9b308ed2, []int{2}
}

func (m *KstorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KstorReply.Unmarshal(m, b)
}
func (m *KstorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KstorReply.Marshal(b, m, deterministic)
}
func (m *KstorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KstorReply.Merge(m, src)
}
func (m *KstorReply) XXX_Size() int {
	return xxx_messageInfo_KstorReply.Size(m)
}
func (m *KstorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_KstorReply.DiscardUnknown(m)
}

var xxx_messageInfo_KstorReply proto.InternalMessageInfo

func (m *KstorReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *KstorReply) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*Status)(nil), "kstor.Status")
	proto.RegisterType((*KstorRequest)(nil), "kstor.KstorRequest")
	proto.RegisterType((*KstorReply)(nil), "kstor.KstorReply")
}

func init() { proto.RegisterFile("kstor/kstor/kstor.proto", fileDescriptor_5f41739f9b308ed2) }

var fileDescriptor_5f41739f9b308ed2 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xad, 0x6d, 0x56, 0x3a, 0x2a, 0xe8, 0x28, 0x18, 0x44, 0xa4, 0x14, 0x84, 0x9e, 0x56,
	0x58, 0x2f, 0x5e, 0xb5, 0x07, 0x0f, 0x7b, 0x91, 0x08, 0xde, 0x63, 0x1b, 0xff, 0xb5, 0x69, 0xea,
	0x26, 0x3d, 0x14, 0xfc, 0xf0, 0x92, 0x69, 0x16, 0xbb, 0x97, 0xf2, 0xde, 0x1b, 0x98, 0x5f, 0xdf,
	0x04, 0x2e, 0x1a, 0xeb, 0xcc, 0xe6, 0x76, 0xf6, 0x5d, 0xf6, 0x1b, 0xe3, 0x0c, 0x32, 0x32, 0xf9,
	0x37, 0x2c, 0x5e, 0x9c, 0x74, 0x83, 0x45, 0x84, 0xa4, 0x32, 0xb5, 0xe2, 0x51, 0x16, 0x15, 0x4c,
	0x90, 0x46, 0x0e, 0x07, 0x5a, 0x59, 0x2b, 0x3f, 0x14, 0xdf, 0xcf, 0xa2, 0x22, 0x15, 0x5b, 0x8b,
	0x57, 0x90, 0x06, 0x59, 0x76, 0x3c, 0xa6, 0xd9, 0x7f, 0x80, 0xe7, 0xc0, 0xac, 0x93, 0x55, 0xc3,
	0x93, 0x2c, 0x2e, 0x52, 0x31, 0x99, 0xfc, 0x17, 0x8e, 0xd6, 0x1e, 0x2a, 0xd4, 0xcf, 0xa0, 0xac,
	0xc3, 0x13, 0x88, 0x4b, 0x5d, 0x13, 0x30, 0x15, 0x5e, 0xfa, 0x64, 0xad, 0xc6, 0xc0, 0xf2, 0xd2,
	0x6f, 0x7a, 0x95, 0xed, 0xa0, 0x02, 0x63, 0x32, 0x78, 0x0d, 0xf0, 0x38, 0x54, 0x8d, 0x72, 0x9d,
	0xd4, 0x8a, 0x27, 0x34, 0x9a, 0x25, 0xbe, 0xcb, 0xb3, 0x74, 0x9f, 0x9c, 0xd1, 0x84, 0x74, 0xfe,
	0x04, 0x10, 0xe8, 0x7d, 0x3b, 0xe2, 0xcd, 0xb6, 0x37, 0xe1, 0x0f, 0x57, 0xc7, 0xcb, 0xe9, 0x38,
	0x53, 0x28, 0x66, 0x47, 0xf9, 0xea, 0xde, 0x4d, 0xf8, 0x23, 0xd2, 0xab, 0x07, 0x60, 0xb4, 0x08,
	0xef, 0x43, 0x9f, 0xd2, 0x68, 0x2d, 0xbb, 0x1a, 0xcf, 0xc2, 0x8e, 0x79, 0xc9, 0xcb, 0xd3, 0xdd,
	0xb0, 0x6f, 0xc7, 0x7c, 0xef, 0x6d, 0x41, 0x6f, 0x70, 0xf7, 0x17, 0x00, 0x00, 0xff, 0xff, 0xbc,
	0xd0, 0x33, 0xad, 0x9e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KstorClient is the client API for Kstor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KstorClient interface {
	KstorCommand(ctx context.Context, in *KstorRequest, opts ...grpc.CallOption) (*KstorReply, error)
}

type kstorClient struct {
	cc *grpc.ClientConn
}

func NewKstorClient(cc *grpc.ClientConn) KstorClient {
	return &kstorClient{cc}
}

func (c *kstorClient) KstorCommand(ctx context.Context, in *KstorRequest, opts ...grpc.CallOption) (*KstorReply, error) {
	out := new(KstorReply)
	err := c.cc.Invoke(ctx, "/kstor.Kstor/KstorCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KstorServer is the server API for Kstor service.
type KstorServer interface {
	KstorCommand(context.Context, *KstorRequest) (*KstorReply, error)
}

func RegisterKstorServer(s *grpc.Server, srv KstorServer) {
	s.RegisterService(&_Kstor_serviceDesc, srv)
}

func _Kstor_KstorCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KstorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KstorServer).KstorCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kstor.Kstor/KstorCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KstorServer).KstorCommand(ctx, req.(*KstorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kstor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kstor.Kstor",
	HandlerType: (*KstorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KstorCommand",
			Handler:    _Kstor_KstorCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kstor/kstor/kstor.proto",
}
